title: Guillaume Briday
email: hello@guillaumebriday.fr
description: > # this means to ignore newlines until "baseurl:".
  Ce blog est à propos des nouvelles technologies, de mes humeurs, de développement Web, de photos...
  En bref, de tout ce dont j'ai envie de parler.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guillaumebriday.fr" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-54003772-2

# Social networks
twitter_username: guillaumebriday
github_username: guillaumebriday
instagram_username: guillaumebriday
amazon_tag: guillaumebrid-21
paypal: guillaumebriday
linkedin: guillaumebriday

# Locale
timezone: Europe/Paris
lang: fr
locale: fr

# Collections
collections:
  photos:
    output: true
    permalink: /photos/:slug
defaults:
  - scope:
      type: photos
    values:
      layout: photo

# Theme
theme: minima
markdown: kramdown
paginate: 15
paginate_path: "/page/:num/"
comments_form: true
permalink: /:title

# plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-minify-html
  - liquid_pluralize

# Folders and formatting
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - gulpfile.js
  - package.json
  - package-lock.json
  - node_modules
include:
  - .htaccess

# Sass
sass:
  style: compressed
  sass_dir: _sass
