# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Guillaume Briday
email: hello@guillaumebriday.fr
description: > # this means to ignore newlines until "baseurl:".
  Ce blog est à propos des nouvelles technologies, de mes humeurs, de développements Web, de photo...
  En bref, de tout ce dont j'ai envie de parler.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.guillaumebriday.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: guillaumebriday
github_username: guillaumebriday
instagram_username: guillaumebriday
amazon_tag: guillaumebrid-21
paypal: guillaumebriday
linkedin: guillaumebriday

# Build settings
markdown: kramdown
theme: minima
paginate: 15
comments_form: true
permalink: /:title
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-minify-html
  - liquid_pluralize
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
google_analytics: UA-54003772-2
sass:
  style: compressed
  sass_dir: _sass
lang: fr
minima:
  date_format: "%d/%m/%Y"
