title: Guillaume Briday
email: hello@guillaumebriday.fr
description: > # this means to ignore newlines until "baseurl:".
  Ce blog est à propos des nouvelles technologies, de mes humeurs, de développement Web, de photos...
  En bref, de tout ce dont j'ai envie de parler.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guillaumebriday.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: guillaumebriday
github_username: guillaumebriday
instagram_username: guillaumebriday
amazon_tag: guillaumebrid-21
paypal: guillaumebriday
linkedin: guillaumebriday

# Build settings
markdown: kramdown
timezone: FR
collections:
  photos:
    output: true
defaults:
  - scope:
      type: photos
    values:
      layout: photo
theme: minima
paginate: 15
paginate_path: "/page/:num/"
comments_form: true
permalink: /:title
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-minify-html
  - liquid_pluralize
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - gulpfile.js
  - package.json
  - package-lock.json
  - node_modules
include:
  - .htaccess
google_analytics: UA-54003772-2
sass:
  style: compressed
  sass_dir: _sass
lang: fr
