- id: 1
  author: Lulu
  date: 2017-02-18 02:15:01
  content: |
    Bonnet merci pour votre article.. cependant comment faire pour communiquer avec le player de la livebox et d'autres périphériques car il y a un prie tre les adresse IP qui ne sont pas sur la même plage!

    Merci

- id: 2
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-02-21 18:05:55
  content: |
    Bonjour, je ne suis pas sûr d’avoir compris votre question, pouvez-vous détailler ? Merci 🙂

- id: 3
  author: Arnaud
  date: 2017-02-28 10:45:59
  content: |
    Bonjour Guillaume, merci pour cet article qui est très bien expliqué. Juste une petite question concernant le player TV Orange. Ou faut il le brancher pour conserver le flux IPTV et VOD. Sur un port LAN du rt1900ac ou sur un port LAN de la LiveBox ?

    Merci de ton aide.

- id: 4
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-03-08 23:33:27
  content: |
    Merci pour ton retour :) J'ai essayé qu'une seule fois et de mémoire ça marche très bien directement sur le Synology. A tester pour être sûr, si tu peux nous confirmer ça, ce serait top !

- id: 5
  author: Paul
  date: 2017-03-08 18:00:43
  content: |
    Bonjour Guillaume,

    Merci et bravo pour la qualité de ton article ! Après plusieurs recherches, tu es le seul à avoir écrit un article sur le sujet.
    J'avais une petite question, sachant que le trafic entrant est redirigé de la Livebox vers le RT1900ac, qu'en est-il du trafic sortant ?
    Dois-je faire mes règles NAT/PAT sur le routeur synology, la livebox, ou les deux ?

    As-tu rencontré des soucis particuliers ?

    Merci de ton retour et encore bravo pour ton travail !

- id: 6
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-03-08 23:31:02
  content: |
    Bonjour Paul,

    Merci pour ton retour ! Alors pour ce qui est des flux sortants le principe est exactement le même, une fois ton routeur dans la DMZ, tu n'as plus rien à faire, tous les échanges qui tu fais via ton Synology seront redirigés sur la livebox puis vers internet. Aucune règle NAT/PAT à configurer et je n'ai, avec cette configuration, eu aucun souci.

    Si tu as d'autres questions n'hésite pas :)

- id: 7
  author: Jordan
  date: 2017-03-10 23:08:14
  content: |
    Rencontres-tu une baisse de débit.

    Car moi ayant presque 1Gbits de bande passante, je passe à 200Mbits en gardant ma LiveBox.

- id: 8
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-03-11 13:00:06
  content: |
    Bonjour, les speedtests en étant sur la Livebox directement ou en passant par le Synology sont significativement les mêmes donc aucun problème pour moi à ce niveau là.

- id: 9
  author: Paul
  date: 2017-03-15 17:20:20
  content: |
    Parfait ! Merci beaucoup pour ton retour.

    As-tu mis en place le LoadBalancing + Failover ?

    Je l'installe ce soir, je te ferais un retour après quelques jours d'utilisation si tu veux. :)

    Bonne journée !

- id: 10
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-03-18 14:36:48
  content: |
    Aucun des deux, je n'en ai pas le besoin. Je suis tout seul (ou presque) à me servir de mon réseau et du NAS. Je sature ma connexion bien trop occasionnellement pour mettre le LoadBalancing en place.

    Et pour le Failover, je n'ai qu'une connexion qui ne coupe que très rarement (voire jamais) et au pire, je relance la Livebox et c'est reparti. :)

    Ah oui ce serait top ! Avec plaisir, merci à toi.

- id: 11
  author: trotroyanas
  author-url: http://www.deco-recup.com
  date: 2017-03-27 22:33:34
  content: |
    Bonsoir Guillaume,

    Merci de cet article je suis exactement dans cette configuration.
    Seulement après avoir fait tout ce que tu as dit, Routeur Syno dans la DMZ de la LiveBox, ajout de règles de transfert de ports du router vers mon nas, rien n'y fait, de l'extérieur c'est tjrs choux blanc.
    Chose étrange il me change bien mon adresse en https ? 8000-> vers 8001 et 5000 -> 5001 pour mon nas mais rien derriere une page d'erreur pour ces 2, et pour mon sftp j'ai le droit à un message "le service que vous demandez ne repond pas.

    Veuillez contacter votre service client" je sais meme pas d'ou il sort ce message.. testé de mon tel en 4g
    Une idée ?

    Merci d'avance
    cH.

- id: 12
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-04-07 17:42:01
  content: |
    Salut, tu as essayé en accès direct pour savoir si le problème venait vraiment de ta configuration ? :)

- id: 13
  author: Guy
  date: 2017-04-06 19:39:54
  content: |
    Bonjour Guillaume,

    Merci pour votre article que j'ai suivi pour configurer mon routeur placé derriere une LiveBox 4
    Tout fonctionne (j'ai de nombreux matériels en câblés et en Wifi), à l'exception de la TV Orange sur la Livebox 4 Player
    Comment cela se fait il ?
    J'avais entendu parler de Vlan/Muxid/ 835 et (838 à 841) à configurer. Comment et ou les configurer ?

    Merci d'avance

    Cordialement

    Guy

- id: 14
  author: Simon
  date: 2017-07-07 14:53:50
  content: |
    Hello,

    J'ai trouvé ton article en tentant de trouver sur internet la solution à mon problème. Pour ma part, j'ai bien fais la même chose que ce que tu indiques, mais le soucis que je rencontre c'est qu'en local le loopback ne fonctionne pas.

    Pour être plus précis, derrière mon Syno RT j'ai un NAS Syno et j'ai mon service de DDNS qui est connecté à OVH (autant sur le RT que sur le NAS). Autant en 4g j'ai accès au NAS autant en local il n'y arrive pas (cf délai trop long...).

    Une idée ?

    Merci à toi

- id: 15
  author: Geoffrey
  date: 2017-10-05 17:06:00
  content: |
    Bonjour Guillaume,

    Avant toute chose, je tenais à vous remercier pour votre tutoriel sur l’installation d’un routeur RT1900AC en DMZ sur une Livebox !

    Merci, car il est en effet très rare de trouver des tutoriels complets comme le vôtre. :)

    Je me permets de vous contacter, pour avoir une information complémentaire qui ne figure pas dans votre tutoriel.

    Vous indiquez, dans la partie « Configuration du routeur RT1900AC »,  je cite : « Dans l’onglet Internet > Connection pensez bien à mettre le Set as default Gateway »

    Je ne comprend pas de quoi s’agit-il ?

    Pour information, je compte effectué la même configuration sur une Bbox :

    IP WAN     |     Bbox  | IP Lan                   -> DMZ sur          IP WAN            |   RT1900AC   |  IP Lan

    5.xx.xxx.xxx/32   |   192.168.1.1/24                         192.168.1.2/24   |                      | 192.168.2.1/24


    Je pense qu’il faut indiquer « Type de connexion » en Manuel, mais je n’arrive pas à voir quoi renseigner à la suite de ceci :

    Adresse IP  :  Wan extérieur ? LAN Bbox ?
    Passerelle : Lan Bbox ?


    Je ne possède pas encore le routeur, mais ça ne saurait tarder, aussi j’anticipe sur ces questions qui vont se poser pour moi très rapidement…

    En vous remerciant sincèrement par avance du tremps consacré à répondre à cette interrogation.

    Bien cordialement.

    Geoffrey

- id: 16
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-10-07 13:55:00
  content: |
    Bonjour Geoffrey,

    Tout d'abord, merci pour tes compliments et ta question, ça fait super plaisir.

    Pour répondre à ta question, le `Set as default Gateway` permet de dire aux éléments du réseau local que c'est par cette adresse (celle du routeur) qu'ils doivent envoyer leurs paquets pour accéder au réseau extérieur et inversement si les paquets viennent de l'extérieur. Sans ça, les clients de ton réseau local pourrons communiquer entre eux, mais pas vers l'extérieur.

    Pour ta configuration, il faut distinguer deux choses, ton interface primaire et ton ip locale. Ton interface primaire doit être l'adresse que tu as définie sur ta livebox (dans ton cas `192.168.1.2`) et ta Gateway doit être `192.168.1.1` (ta livebox). Et pour ton ip locale tu peux mettre ce que tu veux, mais dans ton exemple c'est `192.168.2.1`.

    Je vais voir si j'ai le temps de faire une modification sur l'article pour expliquer ce point.

    En espérant avoir répondu à ta question :)

- id: 17
  author: Olivier
  date: 2017-10-26 09:20:01
  content: |
    Merci pour ton tuto, il m'a bien servi pour connecter mon RT1900 sur ma livebox zen. J'ai pu le mettre à jour et m'apercevoir que SRM a bien évolué.

- id: 18
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-11-03 20:54:00
  content: |
    Merci Olivier pour ton commentaire. Oui SRM et DSM évoluent très vite en restant très stable c'est super agréable à l'usage !

- id: 19
  author: Pilou
  date: 2017-11-27 11:00:46
  content: |
    Bonjour Guillaume, merci pour le tuto très complet.

    Je suis intéressé par ce Routeur, mais une question reste ouverte pour moi.

    Je souhaiterais l'installer dans le cadre d'un Gite, et donc n'ouvrir que le réseau invité au client.

    Est-ce que celui-ci est bridé?

    J'aimerais interdire l'accès au P2P (Hadopi), aux sites illictes (genre pédo-pornographie), mais laisser quand même certains accès (Steam par exemple).

    Est-ce qu'il le permet?

    Enfin dernière question: Si jamais un client contourne les protections, est-ce qu'il y a un journal de connexion (moins consommateur de bande passante que le CTF).

    Merci d'avance pour ton retour.

- id: 20
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-11-27 20:00:00
  content: |
    Bonjour Pilou merci pour ton retour !

    Alors, je viens de faire le test sur SRM (1.1.5-6542 Update 4), la seule option que j'ai trouvé par rapport au réseau invité à ce niveau-là c'est de l'isoler du réseau principal...
    Je crois que ce n'est pas encore possible sur SRM, mais je sais que pfSense le permet, en revanche on est à des années-lumière de la simplicité et de l'ergonomie de SRM en terme de mise en place.

    Par contre, tu peux mettre des filtres sur certaines catégories de sites ou service par défaut sur tous les appareils, mais le couper pour certains (les tiens). Tu peux aussi filtrer les sites par url. Je m'en sers personnellement pour bloquer la publicité et le phishing par exemple. Tu peux trouver plus d'infos ici : [https://www.synology.com/en-us/knowledgebase/SRM/help/SRM/RouterApp/parentalcontrol_keyword](https://www.synology.com/en-us/knowledgebase/SRM/help/SRM/RouterApp/parentalcontrol_keyword)

    Pour la seconde question, à ma connaissance tu ne pourras pas avoir un journal de connexion sans CTF, tu pourras avoir un "top" des sites visités, mais pas historisés et groupés par devices.

    J'espère avoir répondu à la question !

    Merci à toi.

- id: 21
  author: Pilou
  date: 2017-11-28 09:27:19
  content: |
    Bonjour Guillaume,

    Ça me semble pas mal ces catégories, ainsi que la possibilité d'ajouter manuellement des URL.

    De ton point de vue, le filtrage fishing (difficile à quantifier) et advertising sont-ils efficaces?

    En ce qui concerne le logging du traffic, j'ai vu sur ton tweet que pour quantifier les 2 vitesses, tu activais les 2 options ("save visited web pages", "enable detection application").

    De ce que je comprends de l'image, c'est justement la 2e option qui a un gros impact sur le débit.

    Je vais surement investir dans cet équipement (j'ai un NAS Syno dont je suis très content, j'ai envie de continuer avec eux), je te ferais part de mon expérience à ce moment-là.

    En tout cas merci dans pour ton retour!

- id: 22
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-11-29 13:27:00
  content: |
    Oui c'est top et ça marche vraiment bien. Effectivement le fishing je n'ai pas eu l'occasion de tester, mais pour la publicité et le reste c'est devenu la règle par défaut sur tous mes appareils.

    Pour la publicité, ça filtre pas tout, mais une partie seulement. Dans la plupart des cas on peut voir que les js sont bloqués même sans bloqueur de pub sur le navigateur. :)

    Ah oui bien-sûr, sur twitter j'ai décoché les deux cases pour faire des tests mais c'est bien la deuxième qui est problématique, la première n'a pas d'influence et permet d'avoir un rapport plus complet.

    Oui j'aimerais bien avoir un retour dans le cas d'un gîte.

    Merci à toi !

- id: 23
  author: Yann@44-Atlantique-PC-Assistance-Informatique
  author-url: https://www.44-atlantique-pc.com
  date: 2018-01-19 18:39:45
  content: |
    Article clair même s’il vaut mieux s’y connaitre un minimum en réseau pour le comprendre! Je réalise à peu près la même chose avec un routeur Netgear connecté derrière la box, mais suis intéressé par ce routeur Synology... intéressant qu’un DDNS soit proposé, c’est dingue qu’un FAI comme Orange ne le propose toujours pas... ça permettrait de pallier aux IP qui ne sont toujours pas fixes (gratuitement) pour les particuliers.

- id: 24
  author: Daniel
  date: 2018-02-28 13:45:23
  content: |
    Bonjour Guillaume,

    Merci pour ce tuto. Je suis dans la même configuration que toi:
    - Livebox pro v4 fibre: quand je suis connecté dessus en ethernet ou wifi n, un speed test donne 200Mb/s en DOWN et 200Mb/s en UP) -> OK
    - Une fois mon routeur rt1900ac (config basique) branché sur la livebox, les débits sont imcompréhensibles:
    speed test avec mon pc connecté en wifi n au RT: 20Mb/s en DOWN et en UP
    speed test avec mon pc connecté en ethernet (Cat6) au RT: 20Mb/s (environ) en DOWN et 200Mb/s en UP :O

    Si tu as une idée, je suis preneur

- id: 25
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2018-03-04 20:27:00
  content: |
    Bonjour Daniel,

    As-tu regardé du côté des CTF ? J'avais des problèmes similaires et ça venait de cette config.

    J'en parle dans l'edit 2 si besoin.

- id: 26
  author: Emmanuel
  date: 2018-03-08 08:48:39
  content: |
    Bonjour à vous, et comme les autres, merci pour ce tuto et ces informations :)
    Pour ma part, j'ai configuré un syno 2600 derrière une livebox.
    Le système est opérationnel et tous mes éléments présent dans le réseau 192.168.2/24 du routeur syno ont bien accès au web et tout transite correctement.
    Malheureusement, lorsque je tente d’accéder depuis l'extérieur à des éléments interne (derrière le syno), je suis tout de même dans l'obligation d'ouvrir les ports depuis la livebox vers le routeur malgré que celui-ci soit mis en DMZ sur cette dernière.
    Je me dis que peut-être vous aviez rencontré cet anomalie ?

    J'avais déjà lu que la livebox ne savait pas gérer correctement la DMZ, il semble que ce soit le cas pour moi, ou alors, il y a un paramétrage de son côté que j'ai oublié :/

    Par avance merci de votre retour :)

- id: 27
  author: Octavi
  date: 2018-04-17 10:03:22
  content: |
    Bonjour, j'ai suivi tout le tutoriel et tout fonctionne bien, sauf que je ne peux accéder à aucun périphérique de l'extérieur. J'ai ouvert plusieurs ports comme le 5001 pour le NAS et il n'y a aucun moyen. J'utilise DynDNS et il est bien configuré car il me marque bien. Je ne sais pas pourquoi mais j'ai un double NAT, je ne comprends pas pourquoi puisque la LIvebox est en mode DMZ pointant vers la RT1900AC. J'ai Internet dans tous les appareils avec câble et avec Wifi. Que pourrait-il être? Y a-t-il une solution?

    Merci beaucoup pour votre travail, c'est génial.

- id: 28
  author: Rank Xerox
  date: 2018-04-18 20:02:15
  content: |
    Bonjour,

    Merci pour ce tuto, sans lequel, je n'aurais pas réussi à configurer le routeur Syno avec ma Livebox.

    Il me reste un problème qui concerne l'IP V6 (en http). En étant connecté directement en filaire sur la LB, l'accès aux adresses IPV6 est nickel, si par contre, je suis connecté coté RT1900ac, toujours en filaire, je n'ai plus d'accès. Avec un navigateur, j'ai le message "La connexion a échoué" sans la moindre attente.

    Côté RT1900ac, et configuration "réseau local", l'activation est impossible. La liste déroulante "prefixe" est vide. Je connais celui de ma box, mais rien pour le saisir.  Dans la partie configuration "internet", le mode est auto, mais ne donne rien. J'ai essayé le mode "manuel" en entrant le prefixe fournir par la LB (/56) et l'adresse WAN IPV6, mais j'ai un message d'erreur (adresse déja prise).

    Donc, je ne sais pas trop comment configurer l'IPV6 sur le RT1900ac.

    Merci pour avance tous conseils, éclairages, ...
    l'IP V6 est configuré en "auto", mais cela ne fonctionne pas.

- id: 29
  author: Rank Xerox
  date: 2018-10-09 11:30:00
  content: |
    Bonjour Guillaume;

    Merci beaucoup pour ce tuto, très utile :)

    A toutes fins utiles : une MaJ des RT2600ac et RT1900ac a été publiée le 4 octobre (firmware 1.2) et semble permettre de remplacer la livebox en DHCP au lieu du PPOE.

    Le nouveau wizzard de configuration permet de configurer l'option 12, l'option 60, l'option 61 et peut être l'option 90 :)

    Penses-tu pouvoir tester ce nouveau firmware et nous faire un retour via une nouvelle update ?

- id: 30
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2018-10-14 23:25:00
  content: |
    Salut Rank !

    J'ai vu les nouveautés, mais je n'ai pas encore pu jouer avec malheureusement !

    Je vais tester dès que j'aurais de nouveau une box chez moi et je ferais un retour si je trouve des trucs intéressant à dire dessus oui !

- id: 31
  author: Darmagezan
  date: 2018-10-30 07:11:00
  content: |
    Bonjour la communauté.

    Je souhaiterais savoir si le rt1900 ou rt2600 propose la création de Vlan ?

    Merci par avance et bonne journée :)

- id: 32
  author: Xavier
  date: 2019-01-319 22:19:00
  content: |
    Bonjour Guillaume,
    
    Je viens de parcourir votre blog. Merci pour votre article concernant le routeur syno que j’ai configuré facilement grâce à votre tuto.
    Je me permets de venir vers vous afin d’avoir votre avis concernant un léger problème avec mon player orange.
    
    En effet, depuis que j’utilise ce routeur, à l’identique de votre tuto, je n’arrive plus à accéder à mon NAS syno depuis le player Orange.
    J’ai essayé de le mettre en IPTV, directement sur le routeur, tout fonctionne correctement sauf l’accès au nas.
    
    Auriez vous une idée afin de ressouder ce désagrément ?
    
    Encore merci pour votre tuto,
    Xavier
