- id: 1
  author: Jennifer
  date: 2018-08-12 16:52:43
  content: |
    Bonjour,

    Merci pour cet article très bien expliqué. Seulement je ne comprends pas ou retrouver les applications téléchargées et comment les ouvrir pour les faire fonctionner sur mon mac.

    Je te remercie par avance pour ton aide

    Jennifer

- id: 2
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2018-07-22 23:50:00
  content: |
    Salut Jennifer,

    Brew s'occupe de tout pour les applications, tu n'aura pas besoin de les retrouver dans le Finder car elles seront directement installées.

    C'est ce qui est vraiment top avec ce système !
